Fix install of clock.tcl (#9)
* workaround for lib/clock.tcl not yet existing during configure using lib_BINARIES in Makefile
* improve path searching for generated clock.tcl
* log error message on failure
* update to 8.6.709
* avoid overloading stubs terminology

diff --git a/.github/workflows/linux-ci.yml b/.github/workflows/linux-ci.yml
--- a/.github/workflows/linux-ci.yml
+++ b/.github/workflows/linux-ci.yml
@@ -56,7 +56,7 @@ jobs:
 
       - name: runtime test
         run: |
-          echo 'if {[catch {package require tclclockmod; clock format -now}]} {puts stderr "ERROR!"; exit 1} else {puts "OK."}' | tclsh
+          echo 'if {[catch {package require tclclockmod; clock format -now} catchResult]} {puts stderr "ERROR! $catchResult"; exit 1} else {puts "OK."}' | tclsh
 
       - name: clean
         run: |
